language: java

jdk:
- oraclejdk9

after_success:
- ./gradlew jacocoTestReport coveralls

deploy:
  provider: heroku
  api_key:
    secure: gvsSpYIjNeAywBArKQPhVG44kl7LlteGMFinaYtlcfu9YBBLW4jT3JBEcLAV8yvkXexiVbDaO0IdojgCbp6uIdRGn4IBBTvSn7Up7JyR1rFlBADC0l19TxoRHJStuQSUm+yVxikq7LT/G79qUVgpEl7KD+CXwRQn4az6OkbVWTXV+7aQHSZvtSptkW7XL/6Gvlk4dxQB9/rB8z41dscQw/snBhdML9n8o80Sk4jVWYghqnjn5F4ADzViVVLoMo+NSzMP5sQNwO1OEPLgiEdFlZRCZz88cC/x6LEOXuW1qyY0kl0cNgpPpfmf2jXbtIZiOs5ZAJrMV0fqIB6xn9KUWaiMTMSSkmxAmD90ZgBgMb3bN4psOgnmGzkYwXYAseSEyLj06QqfGcM7QjQC/n3lmVjRud8ILZyVHsnseaToDKQTZ3FDSTYV/xXEz5d46aF9drumOBW8SSrv9XZYT1u1ezyUo5Hm4+DtralvGSO81Hrl8PfVtzn23Zy47dwMWcTh0NGWajSe6SK84isAeujnwaarreyR/ARTGXEddSIA1SiqMsNzWsC9f0iD+i2Aq0euzIm4N2Zb60MtvbUS5QCO5ru1mzj5mxNnhknU02skRSMzsVG8UPYpcVrFyspYZo4+e7NOdJO62O2zWrO7rkLN8emokbVf3xUXGIN3QR2iz5c=
